### ISSUE TITLE
Homepage > Tile Navigation Style

### ISSUE THREAD

**Issue by jpyo** [SCarrero/home#12]
On the desktop breakpoints, these tiles should be square, connected and overlapping the hero image similarly to the steps-tile-navigation seen on the detail pages.

current:
![image](https://user-images.githubusercontent.com/8764348/71204398-0ee72e00-226e-11ea-9cc2-c42c79165f78.png)

in design:
![image](https://user-images.githubusercontent.com/8764348/71204455-26beb200-226e-11ea-9d9a-585e02aa1407.png)
https://freddiemaccreatives.invisionapp.com/share/3HV9J7UXUCM#/397766497_Homepage

**Comment by SCarrero** [comment]
I thought you had them broken apart at all breakpoints?  
So confusing since the comps are all from different times and different iterations of the design.

**Comment by SCarrero** [comment]
Updated. Please review.

**Comment by jpyo** [comment]
@SCarrero looks good, just one minor thing. The grey borders inbetween the tiles look like it is 2px because both 1px edges from the tiles are meeting in the middle. Can we make them look like 1px just for the middle lines?

**Comment by SCarrero** [comment]
please review
