### ISSUE TITLE
Global > Breadcrumb styling

### ISSUE THREAD

**Issue by jpyo** [SCarrero/home#13]
current:
![image](https://user-images.githubusercontent.com/8764348/71205637-c4b37c00-2270-11ea-9668-f406d9862b3d.png)

design:
![image](https://user-images.githubusercontent.com/8764348/71205893-57ecb180-2271-11ea-8b02-5e05e50b9c99.png)

increase font weight and add letter-spacing to the breadcrumb style
``` 
font-family: Gibson-Medium;
font-size: 12px;
letter-spacing: 1.75px;
```

**Comment by SCarrero** [comment]
Can we keep the letter spacing more normal at narrow mobile sizes, and then increase it up to 1.75 as the page gets wider?

**Comment by jpyo** [comment]
we can try decreasing the letter spacing but let's try stacking the words onto 2 lines first.

**Comment by SCarrero** [comment]
Updated. Please review.

**Comment by jpyo** [comment]
looks good. closing
