### ISSUE TITLE
Main Navigation > Float divs to left and right sides

### ISSUE THREAD

**Issue by jpyo** [SCarrero/home#14]
![image](https://user-images.githubusercontent.com/8764348/71207070-04c82e00-2274-11ea-8706-db0ab5414989.png)
The menu box and logo box should be locked to the sides of the browser and stay there as the windows is resizes larger.

**Comment by SCarrero** [comment]
really? that is not how Cinzia's designs looked.  
So, on a wide display, will the hamburger navigation then travel from the far right edge of the window where the dead white space is, and not from  the right edge of the content area?

**Comment by jpyo** [comment]
I wasn't made aware of this behavior from Cinzia so closing this @SCarrero
