### ISSUE TITLE
Global > Top Hero images should grow with browser width

### ISSUE THREAD

**Issue by jpyo** [SCarrero/home#15]
![image](https://user-images.githubusercontent.com/8764348/71207238-6a1c1f00-2274-11ea-94e3-4651f39a202d.png)
remove the max-width on all hero images so that the image stay flush to the sides of the browser at all times. 
there should not be white space on the sides on the image

**Comment by SCarrero** [comment]
This is also a change from Cinzia's original recommendations. 
We will definitely have problems finding images that will work well very wide widths.   Its why we used more generic background images blended with an overlay color on FM.  We couldn't find good images to make it work.  Simply finding one image for the corporate homepage hero is often a struggle.

**Comment by jpyo** [comment]
Sorry I wasn't aware of this @SCarrero ill close these for now.
