### ISSUE TITLE
Section Landing Page > Step Bubble Text Style

### ISSUE THREAD

**Issue by jpyo** [SCarrero/home#30]
it looks like the font inside the bubbles is using a font that we don't use on the site. It should be Gibson Medium. Also nudge the number over to the left a bit so it is centered within the bubble
![image](https://user-images.githubusercontent.com/8764348/72356360-2374e580-36b7-11ea-9b14-6386b7b3a0a9.png)

**Comment by SCarrero** [comment]
sorry -- copied part of the design over from a prototype page I built and didn't adjust the font.

**Comment by SCarrero** [comment]
please review. Redid these to be more flexible -- they are now css only, instead of using an SVG for each circle and number.
