### ISSUE TITLE
Share Widget (mobile) > Styling

### ISSUE THREAD

**Issue by jpyo** [SCarrero/home#32]
- decrease font to .8rem.
- edit line-height of label to 1.5 to center to pipe-line.
- add margin of 30px on top of the widget to give distance between the dropdown.
- edit padding-left on icons to 1rem to give more space between them.

![image](https://user-images.githubusercontent.com/8764348/72360181-984b1e00-36bd-11ea-86a1-21fefc96e9f2.png)

**Comment by SCarrero** [comment]
please review.
