### ISSUE TITLE
Footer > Link Hover States

### ISSUE THREAD

**Issue by jpyo** [SCarrero/home#33]
- Let's have these text links turn blue on hover (#00a6e2)
- and use the same hover colors you have on the share widget for the social icons
- The hovers should also have a .2s ease-in-out applied to them

![image](https://user-images.githubusercontent.com/8764348/72360702-5a022e80-36be-11ea-9202-eb1ae4ffa165.png)

**Comment by SCarrero** [comment]
please review.
