### ISSUE TITLE
Main Navigation > Tile Size on Large Desktop

### ISSUE THREAD

**Issue by jpyo** [SCarrero/home#39]
Im thinking we should bump up the size of the tiles to something like 15rem on large desktop so the grey space isnt to large

![image](https://user-images.githubusercontent.com/8764348/72369894-0fd57900-36cf-11ea-8a43-a096e7bbc5d1.png)

**Comment by SCarrero** [comment]
please review.  They now size up/down as the screen width gets wider/narrow.
