### ISSUE TITLE
Homepage > Animated Illustrations

### ISSUE THREAD

**Issue by jpyo** [SCarrero/home#43]
Just using this as a place to keep the animated examples for the Illustrations

![illustration-buying-handphone](https://user-images.githubusercontent.com/8764348/72639062-cedd9e80-3932-11ea-9256-6345ddf54d7a.gif)
![illustration-help](https://user-images.githubusercontent.com/8764348/72639064-cedd9e80-3932-11ea-84d3-9ac791b7bea8.gif)
![illustration-owning](https://user-images.githubusercontent.com/8764348/72639065-cf763500-3932-11ea-9c6e-c23dd3ee50fa.gif)
![illustration-refinancing](https://user-images.githubusercontent.com/8764348/72639066-cf763500-3932-11ea-980d-cc93cf5cb80f.gif)
![illustration-renting](https://user-images.githubusercontent.com/8764348/72639068-cf763500-3932-11ea-94df-e8a56a719459.gif)
![illustration-selling](https://user-images.githubusercontent.com/8764348/72639069-cf763500-3932-11ea-87f6-90b03c3e8fec.gif)

**Comment by SCarrero** [comment]
@jpyo can we close this issue?  It's been pending your review since Feb 20.

**Comment by SCarrero** [comment]
@jpyo Haven't heard back, so closing issue.
