### ISSUE TITLE
Homepage > Increase Spacing between content

### ISSUE THREAD

**Issue by jpyo** [SCarrero/home#44]
On large desktop, can we increase the spacing between the illustration/copy blocks to about double what it is now? Want to give the copy blocks some more space so they don't read into each other.

![image](https://user-images.githubusercontent.com/8764348/72826782-79adcf80-3c47-11ea-9184-c5736e891008.png)

**Comment by SCarrero** [comment]
please review.

**Comment by jpyo** [comment]
@SCarrero the new spacing inbetween looks good, but is the entire section still centered in the space? I looks like it might be slightly too far to the left.

**Comment by SCarrero** [comment]
Everything is centered and equally spaced -- could just appear to the left because we left aligned all text and let the right edge be jagged. 
![image](https://user-images.githubusercontent.com/20446484/73017806-6a1cbb00-3dee-11ea-8e2d-3b5ab5c735d4.png)

**Comment by jpyo** [comment]
@SCarrero ok that's what I figured. Once we finalize the copy we might want to look at faking it so it looks visually centered instead of going with the code, but we'll see.
