### ISSUE TITLE
Global > Hover transition speed

### ISSUE THREAD

**Issue by jpyo** [SCarrero/home#47]
@SCarrero can you tell me what the current speed of the easing is set at for the image and arrow hovers? I'm thinking it should be slightly quicker but I can't find it in inspect mode.

![image](https://user-images.githubusercontent.com/8764348/72827837-83383700-3c49-11ea-989e-07f16eb56de0.png)
![image](https://user-images.githubusercontent.com/8764348/72827845-88958180-3c49-11ea-9d12-30d5f3bd471b.png)

**Comment by SCarrero** [comment]
the arrow, the title color, and the image container movement are all set to  0.25s ease-in.

**Comment by jpyo** [comment]
@SCarrero any chance you can screenshot how I can find that property in inspect so I can fiddle with it?

**Comment by SCarrero** [comment]
For the image speed, select the box that contains the svg:
![image](https://user-images.githubusercontent.com/20446484/72913714-8eec3200-3d0b-11ea-9007-3ee59f951290.png)

For the arrow, select the arrowhead or the arrow line inside the svg.
![image](https://user-images.githubusercontent.com/20446484/72913898-ce1a8300-3d0b-11ea-9a84-6e25bc687d50.png)

**Comment by SCarrero** [comment]
For the title's color change, just select the H3.

**Comment by jpyo** [comment]
@SCarrero let's change the arrow and h3 to `.2s ease-in-out`

**Comment by SCarrero** [comment]
please review.
