### ISSUE TITLE
Hamburger Nav > (mobile) Disable Scroll in Menu

### ISSUE THREAD

**Issue by jpyo** [SCarrero/home#50]
On mobile, we need to disable scrolling or pin the menu to the top so the user cannot scroll down into the blurred area. The menu should take the full vertical space of the device (on both the tiles and sub-level)

![image](https://user-images.githubusercontent.com/8764348/72829131-2ab66900-3c4c-11ea-9b08-8d786a87c9f9.png)

**Comment by SCarrero** [comment]
That may prevent users from getting to the lower items on some of the subnavs -- we'll need to test if all the buying links are visible on mobile if scrolling is disabled when nav is open.

**Comment by SCarrero** [comment]
if I test on an iPhone 5, the nav is already taller than the height, with the 6 icons.  Should I reduce their height and width to insure everything fits on smaller phones?
(and should I only add that rule for portrait?  Users in landscape won't be able to get to most of hte nav otherwise.)

**Comment by jpyo** [comment]
@SCarrero well, i guess it shouldnt completely disable scrolling, rather it should prevent you from scrolling past the section and into the blurred area, if that makes sense.

**Comment by SCarrero** [comment]
scrolling outside of the expanded navs is now limited. If a user's layout doesn't have sufficient height for the nav or subnavs, the nav subsection will scroll instead of the full page.   (mainly noticeable on smaller mobile phones in landscape mode)
