### ISSUE TITLE
Homepage > About Section Button Color

### ISSUE THREAD

**Issue by jpyo** [SCarrero/home#52]
Something happened to the button color on the about section and it is now grey. Change it back to blue

![image](https://user-images.githubusercontent.com/8764348/72830340-841f9780-3c4e-11ea-8e7c-28a0ea410082.png)

**Comment by SCarrero** [comment]
please review.

**Comment by jpyo** [comment]
@SCarrero it's blue now, but these are still showing as a dark blue. It should be #00A6E2
![image](https://user-images.githubusercontent.com/8764348/73010198-f4a9ee00-3ddf-11ea-87ed-7a636d9614a2.png)

**Comment by SCarrero** [comment]
weird -- in my local build it's correct. Must be a typo messing up the prod css generation. Let me take a look.

**Comment by SCarrero** [comment]
ok -- should be corrected now. please review.
