### ISSUE TITLE
Tools & Resources > Button Styling

### ISSUE THREAD

**Issue by jpyo** [SCarrero/home#53]
I think we need to check the button color on this component and other areas this style is used. The blue color should be #00A6E2 but it is showing as a darker color. Also, can we align all the buttons to the lowest button? 

![image](https://user-images.githubusercontent.com/8764348/72830593-090ab100-3c4f-11ea-854f-d7f834c624bf.png)

**Comment by SCarrero** [comment]
Right now they are just a set number of pixels below where the text cuts off.  I can flexbox everything to do what you've asked, but this content will actually vary on each landing page, so it may look weird when one section is much longer or shorter than the others. (this one just happens to have the blurbs fairly similar in length, but I wouldn't expect that to be the case when the actual content is in each column)

**Comment by jpyo** [comment]
@SCarrero Good point, let's leave it alone for now and re-discuss once we have the actual content. Ideally, we will have the content team write to a character amount that is consistent for each.

**Comment by SCarrero** [comment]
changed color for now. please review.

**Comment by SCarrero** [comment]
closing now that content team has written blurbs to be of similar length.
