### ISSUE TITLE
Global > Accordion Style

### ISSUE THREAD

**Issue by jpyo** [SCarrero/home#55]
Match the spacing that is on top of the circle to below the circle. And preview 3 lines instead of two. 
![image](https://user-images.githubusercontent.com/8764348/72839534-72df8680-3c60-11ea-9b8d-0bd9377b6ac2.png)

**Comment by SCarrero** [comment]
No problem -- these were what best I could do from memory, since the invision comps weren't up to date. Now that they are updated, I can redo these.

**Comment by SCarrero** [comment]
please review
