### ISSUE TITLE
Blog Component > Image Hover State

### ISSUE THREAD

**Issue by jpyo** [SCarrero/home#56]
In addition to the existing hover animations (title+arrow), can we add a scaling effect to the image?
![blog-hover](https://user-images.githubusercontent.com/8764348/72840224-c3a3af00-3c61-11ea-9733-90cd1b321dd4.gif)

**Comment by SCarrero** [comment]
are you using some type of bezier curve for the timing on that effect?  I've tried ease, ease-in, ease-in-out, but none of them quite match what you've got above.

**Comment by jpyo** [comment]
@SCarrero It should be ease-in-out for .2s 

Its similar to the 'basic' example on this demo: https://w3bits.com/labs/css-image-hover-zoom/

**Comment by SCarrero** [comment]
ok -- I had it as ease-in-out, but it doesn't have the bouncy feel of your example.  I'll post shortly.

**Comment by SCarrero** [comment]
please review.
