### ISSUE TITLE
Main Nav > Letter-spacing on menu/search

### ISSUE THREAD

**Issue by jpyo** [SCarrero/home#9]
![image](https://user-images.githubusercontent.com/8764348/71195552-2a493d80-225c-11ea-9d9b-aa9aa20d15bd.png)
Add a letter-spacing of 2px to the words 'search' and 'menu'
`letter-spacing: 2px;`

**Comment by SCarrero** [comment]
Updated. Please review.

**Comment by jpyo** [comment]
looks good
